// -------------------------------------------------------------------
//
//  Spike Header File - Contains all native methods definition
//
// Copyright (c) 2012-2013, Jorge Garrido <zgbjgg@gmail.com>
// All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// -------------------------------------------------------------------

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zgbjgg_spike_SpikeNative */

#ifndef _Included_com_zgbjgg_spike_SpikeNative
#define _Included_com_zgbjgg_spike_SpikeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zgbjgg_spike_SpikeNative
 * Method:    createProcess
 * Signature: (Ljava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_zgbjgg_spike_SpikeNative_createProcess
  (JNIEnv *, jclass, jstring, jstring, jobjectArray, jobjectArray);

/*
 * Class:     com_zgbjgg_spike_SpikeNative
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zgbjgg_spike_SpikeNative_test 
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
